# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Sanskar's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Sanskar Anil Nalkande
headline: headline message
description: >- # dont remove this line. this will ignore all new lines until the next section
  I am a Mechanical Engineer with a passion for design, fabrication, and automation. My expertise lies in 3D printing, robotics, 
  materials testing, and control systems, combining hands-on prototyping with computational analysis.
  I have processed 2,500+ 3D prints, optimized fabrication workflows, and worked with a range of 3D printers and slicing software. 
  I have also designed robotic manipulators, high-strain-rate test fixtures, and flexure-based micro-mirrors, using FEA simulations 
  in ANSYS to validate designs. My experience includes automating control systems with LabVIEW and MATLAB, 
  as well as modeling MIMO systems for precise response predictions.
  From building a go-kart from scratch to refurbishing legacy 3D printers, I enjoy tackling engineering challenges that push the limits 
  of efficiency, accuracy, and manufacturability. My work blends simulation, automation, and hands-on problem-solving to create practical, 
  high-performance systems.
  I’m always looking for opportunities to apply my skills to innovative projects in robotics, automation, and product development. 
  Let’s connect and build something groundbreaking!

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: https://drive.google.com/file/d/13Z3duVzh-gguPU5r03oJVEE6rV9rd3DS/view?usp=sharing


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: sanskar-nalkande-4960401b0    # https://www.linkedin.com/in/{your url slug} 
  github: Sanskar201    # https://github.com/{your url slug} 
  stackoverflow:       # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: 3D Modeling and Simulations
    tools:
    - Fusion 360 (Autodesk)
    - Inventor (Autodesk)
    - ANSYS
    - Simulink
  - category: Programming Languages
    tools:
    - MATLAB
    - LabVIEW
    - Python
    - C++
    - C
  - category: Prototyping
    tools:
    - CNC
    - FDM 3D Printing
    - SLA 3D Printing
    - Laser Cutting
    - Arduino / Raspberry Pi
    - Breadboarding for circuit testing
  - category: Data Acquisition
    tools:
    - NI DAQ (LabVIEW)
    - NI 9237
    - NI 9212
    - Vishay P3
    - Oscilloscope
    - Strain Gauge
    - Load Cell


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/{8-digit key}



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
